
crsType = {}
data = list()
data.append("素養通識-生活藝能及應用")
data.append("校必(英)")
data.append("跨學院通識(教)")
data.append("軍訓選修")
data.append("產業必修")
data.append("社會學科")
data.append("人文學科或自然學科")
data.append("組選修")
data.append("校必(國)")
data.append("校必(通識)")
data.append("組必修")
data.append("跨學院通識(社體)")
data.append("跨學院通識(管)")
data.append("跨學院通識(文)")
data.append("跨學院通識(科技)")
data.append("系選修")
data.append("師培選修")
data.append("體育選修")
data.append("跨學院通識(工)")
data.append("語文選修")
data.append("跨學院通識(理)")
data.append("系必修")
data.append("外系選修")
data.append("素養通識-文化美學與文明")
data.append("師培必修")
data.append("自由選修")
data.append("校必(體)")

for i in range(len(data)):
    crsType[i] = data[i]

print(crsType)
